adminlocker.settings:
  type: config_object
  label: 'AdminLocker settings'
  mapping:
    adminlocker:
      type: mapping
      mapping:
        adminlocker_block:
          type: longtext
          label: 'AdminLocker blocklist'
        adminlocker_allow:
          type: longtext
          label: 'AdminLocker allowlist'